### ISSUE TITLE
Notice: ob_end_flush()

### ISSUE THREAD

**Issue by junaidbhura** [sparanoid/relative-url#1]
I get a notice for  `ob_end_flush()` if the buffer was terminated elsewhere.

The full error is:

` Notice: ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in /xx/wp-content/plugins/relative-url/relative-url.php on line 133`

**Comment by sparanoid** [comment]
Can you describe In which situations will you get this error?

@ symbol just suppresses the error but the problem still exists.

**Comment by junaidbhura** [comment]
@sparanoid This occurs when the output buffer is already closed somewhere else before this plugin gets a chance to close it.

It's not an error, it's a notice, which shows up if you have WP_DEBUG turned on.

You can see from the documentation for `ob_end_flush` ( http://php.net/manual/en/function.ob-end-flush.php ) under "Errors/Exceptions" it returns an E_NOTICE if it fails.

There is no problem, it's just a notice, which the @ suppresses.
